{% set name = "papi" %}
{% set version = "7.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://icl.utk.edu/projects/papi/downloads/papi-{{ version }}.tar.gz
  sha256: 5818afb6dba3ece57f51e65897db5062f8e3464e6ed294b654ebf34c3991bc4f

build:
  number: 1
  skip: true  # [win44]
  run_exports:
    - {{ pin_subpackage('papi', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/include/papi.h
    - test -f ${PREFIX}/lib/libpapi.so
    - test -f ${PREFIX}/lib/pkgconfig/papi.pc
    - test -f ${PREFIX}/share/papi/papi_events.csv
    - papi_version

about:
  home: https://icl.utk.edu/papi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Performance Application Programming Interface

extra:
  recipe-maintainers:
    - apmorton
